# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MvnTui < Formula
  desc "Terminal UI for Maven - make common workflows fast and discoverable"
  homepage "https://github.com/AR0106/mvn-tui"
  version "1.0.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/AR0106/mvn-tui/releases/download/v1.0.6/mvn-tui_Darwin_x86_64.tar.gz"
      sha256 "fdf48ba9c14ebf0f47afe2895c1bc7fde3d02cb31639d46f53190ec535d91d44"

      def install
        bin.install "mvn-tui"
      end
    end
    on_arm do
      url "https://github.com/AR0106/mvn-tui/releases/download/v1.0.6/mvn-tui_Darwin_arm64.tar.gz"
      sha256 "627f3045f97e3fabd05faff56482e3e6f627139cd91c7e544178d49884668586"

      def install
        bin.install "mvn-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AR0106/mvn-tui/releases/download/v1.0.6/mvn-tui_Linux_x86_64.tar.gz"
        sha256 "22f75fbc8f0dc83d0e69355925909704f54b983f537022bc750af2d5e23d5917"

        def install
          bin.install "mvn-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AR0106/mvn-tui/releases/download/v1.0.6/mvn-tui_Linux_arm64.tar.gz"
        sha256 "5196fafa9c7b9f98fdbac1f905e2b038b6eabd5f89c614fa0d8743acc26f1297"

        def install
          bin.install "mvn-tui"
        end
      end
    end
  end

  def caveats
    <<~EOS
      mvn-tui is a Terminal User Interface for Maven.

      To get started:
        cd /path/to/maven/project
        mvn-tui

      Or create a new project:
        mkdir my-project && cd my-project
        mvn-tui

      For more information, visit:
        https://github.com/AR0106/mvn-tui
    EOS
  end

  test do
    system "#{bin}/mvn-tui", "--version"
  end
end
