# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MvnTui < Formula
  desc "Terminal UI for Maven - make common workflows fast and discoverable"
  homepage "https://github.com/AR0106/mvn-tui"
  version "1.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/AR0106/mvn-tui/releases/download/v1.0.5/mvn-tui_Darwin_x86_64.tar.gz"
      sha256 "28702a6fdab6528dbf36c178f14d01b9e2981c8b22c40b327001751f37337cb4"

      def install
        bin.install "mvn-tui"
      end
    end
    on_arm do
      url "https://github.com/AR0106/mvn-tui/releases/download/v1.0.5/mvn-tui_Darwin_arm64.tar.gz"
      sha256 "d058809f1daf9a2484883b122975fdca79c4092d031d12992d44075a716071b8"

      def install
        bin.install "mvn-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AR0106/mvn-tui/releases/download/v1.0.5/mvn-tui_Linux_x86_64.tar.gz"
        sha256 "f50862ca4a0bd2d65565ea2f451727cd480177ab5e01b57a3ff00ebfcf1e3071"

        def install
          bin.install "mvn-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AR0106/mvn-tui/releases/download/v1.0.5/mvn-tui_Linux_arm64.tar.gz"
        sha256 "c19e87181330d3dc0cc25598e0511e10528a88ead53e1aa342f326052a4de576"

        def install
          bin.install "mvn-tui"
        end
      end
    end
  end

  def caveats
    <<~EOS
      mvn-tui is a Terminal User Interface for Maven.

      To get started:
        cd /path/to/maven/project
        mvn-tui

      Or create a new project:
        mkdir my-project && cd my-project
        mvn-tui

      For more information, visit:
        https://github.com/AR0106/mvn-tui
    EOS
  end

  test do
    system "#{bin}/mvn-tui", "--version"
  end
end
