# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MvnTui < Formula
  desc "Terminal UI for Maven - make common workflows fast and discoverable"
  homepage "https://github.com/AR0106/mvn-tui"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/AR0106/mvn-tui/releases/download/v1.1.0/mvn-tui_Darwin_x86_64.tar.gz"
      sha256 "0a4fe29f80972a8729fdcb03e1d84d61fcbbc872e3b787fa7a4153e7cbefe624"

      def install
        bin.install "mvn-tui"
      end
    end
    on_arm do
      url "https://github.com/AR0106/mvn-tui/releases/download/v1.1.0/mvn-tui_Darwin_arm64.tar.gz"
      sha256 "139add5e08046718c53c890e245c0ea748d4ddcaac12ed37925eb34f6e30aff6"

      def install
        bin.install "mvn-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AR0106/mvn-tui/releases/download/v1.1.0/mvn-tui_Linux_x86_64.tar.gz"
        sha256 "d26636c56eb18313dcdcfbe481275df03e97e96a3cf8a3ad04afc75bc161aa65"

        def install
          bin.install "mvn-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AR0106/mvn-tui/releases/download/v1.1.0/mvn-tui_Linux_arm64.tar.gz"
        sha256 "00633a0e305570b705bbb5e1195a98e493367a49f27828c677d01010fba5484f"

        def install
          bin.install "mvn-tui"
        end
      end
    end
  end

  def caveats
    <<~EOS
      mvn-tui is a Terminal User Interface for Maven.

      To get started:
        cd /path/to/maven/project
        mvn-tui

      Or create a new project:
        mkdir my-project && cd my-project
        mvn-tui

      For more information, visit:
        https://github.com/AR0106/mvn-tui
    EOS
  end

  test do
    system "#{bin}/mvn-tui", "--version"
  end
end
